coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "tests/**"
  - "uninstall.php"

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true
