name: plugin-name
type: php
docroot: .ddev/wordpress
php_version: "8.4"
hooks:
    pre-start:
        - exec-host: mkdir -p .ddev/wordpress
        - exec-host: ddev add-on get apermo/ddev-orchestrate 2>/dev/null || true
