name: Lighthouse CI

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    lhci:
        uses: apermo/reusable-workflows/.github/workflows/reusable-lhci.yml@main
        with:
            setup-wp-env: true
            config-path: .lighthouserc.js
