name: Prerelease

on:
    workflow_dispatch:
        inputs:
            label:
                description: 'Prerelease label (e.g. beta.1, RC.1)'
                required: true

jobs:
    prerelease:
        uses: apermo/reusable-workflows/.github/workflows/reusable-prerelease.yml@main
        permissions:
            contents: write
            pull-requests: write
